version: '3'
services:
  server:
    build:
      context: ./cooking
      args:
        ENV: ${ENV}
    container_name: cooking
    environment:
      - ENV=$${ENV}
    ports:
      - 8080:8080

  web:
    build:
      context: ./cooking-web
      args:
        ENV: $${ENV}
    container_name: cooking-web
    ports:
      - 4200:80
    links:
      - server